version: '3.1'

volumes:
  postgres-data:

networks:
  backend:

services:
  postgres:
    image: postgres:9.5-alpine
    ports:
      - 5450:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks: [ "backend" ]
    environment:
      POSTGRES_PASSWORD: p0stgr3s
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: billyabm/rails-solr-elasticsearch
    volumes:
      - .:/usr/src
    networks: [ "backend" ]
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    command: rails server -p 3000 -b 0.0.0.0
    ports: [ "300:3000" ]
    environment:
      DATABASE_URL: postgres://postgres:p0stgr3s@postgres:5432/rails_solr_elasticsearch
      RAILS_ENV: development
      RACK_ENV: development
      RAILS_LOG_TO_STDOUT: "true"