version: '3.1'

volumes:
  postgres-data:
  gems:
  solr-data:

networks:
  backend:

services:
  postgres:
    image: postgres:9.5-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks: [ "backend" ]
    environment:
      POSTGRES_PASSWORD: p0stgr3s
  
  web: &app
    build:
      context: .
      dockerfile: Dockerfile
    image: billyabm/rails-solr-elasticsearch
    volumes:
      - .:/usr/src
      - gems:/usr/local/bundle
    networks: [ "backend" ]
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - solr
    command: rails server -p 3000 -b 0.0.0.0
    ports: [ "3000:3000" ]
    environment:
      DATABASE_URL: postgres://postgres:p0stgr3s@postgres:5432/rails_solr_elasticsearch
      RAILS_ENV: development
      RACK_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      SOLR_CORE_NAME: ${SOLR_CORE_NAME:-rails-app-core}

  solr:
    image: solr
    ports:
     - "8983:8983"
    networks: [ "backend" ]
    volumes:
      - solr-data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ${SOLR_CORE_NAME:-rails-app-core}
