production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: solr
    port: 8983
    log_level: INFO
    path: <%= "/solr/#{ENV.fetch("SOLR_CORE_NAME") { 'rails-app-core' }}" %>

test:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    path: /solr/test
    